package main

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// committed is the file this generator owns.
const committed = "../../ast/expr.go"

// TestGeneratedFileIsUpToDate is the guard against hand-editing ast/expr.go.
// You will do it at 1am in chapter 9; this fails the build when you do.
func TestGeneratedFileIsUpToDate(t *testing.T) {
	t.Parallel()

	want, err := os.ReadFile(committed)
	if err != nil {
		t.Fatalf("reading %s: %v", committed, err)
	}

	got, err := render(exprs)
	if err != nil {
		t.Fatalf("render: %v", err)
	}

	if string(got) != string(want) {
		t.Errorf("%s is out of date or was edited by hand.\nRun: go generate ./...\n\n%s",
			committed, firstDiff(string(want), string(got)))
	}
}

// TestGenerateWritesTheFile exercises the write path into a temp dir.
func TestGenerateWritesTheFile(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	if err := generate(dir, exprs); err != nil {
		t.Fatalf("generate: %v", err)
	}

	got, err := os.ReadFile(filepath.Join(dir, "expr.go"))
	if err != nil {
		t.Fatalf("generated file missing: %v", err)
	}

	want, err := os.ReadFile(committed)
	if err != nil {
		t.Fatalf("reading %s: %v", committed, err)
	}

	if string(got) != string(want) {
		t.Errorf("generate() output differs from the committed %s", committed)
	}
}

// TestGeneratedHeader pins the exact prefix that gofmt, linters and GitHub
// diffs recognise as machine-generated.
func TestGeneratedHeader(t *testing.T) {
	t.Parallel()

	src, err := render(exprs)
	if err != nil {
		t.Fatalf("render: %v", err)
	}

	const want = "// Code generated by cmd/genast. DO NOT EDIT."
	if first, _, _ := strings.Cut(string(src), "\n"); first != want {
		t.Errorf("first line = %q, want %q", first, want)
	}
}

// TestRenderEmitsEveryNode checks the spec table actually reaches the output:
// a struct, a field, an Accept, a marker and a visitor method per node.
// Patterns are regexps because gofmt aligns the columns.
func TestRenderEmitsEveryNode(t *testing.T) {
	t.Parallel()

	src, err := render(exprs)
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	got := string(src)

	for _, n := range exprs.Nodes {
		pats := []string{
			`type ` + n.Name + ` struct \{`,
			`func \(e \*` + n.Name + `\) Accept\(v ExprVisitor\) any \{ return v\.Visit` + n.Name + `Expr\(e\) \}`,
			`func \(e \*` + n.Name + `\) isExpr\(\)\s+\{\}`,
			`\n\tVisit` + n.Name + `Expr\(e \*` + n.Name + `\) any\n`,
		}
		for _, f := range n.Fields {
			// e.g. "\tLeft     Expr\n" — gofmt pads the name column.
			pats = append(pats, `\n\t`+f.Name+`\s+`+regexp.QuoteMeta(f.Type)+`\n`)
		}
		for _, pat := range pats {
			if !regexp.MustCompile(pat).MatchString(got) {
				t.Errorf("node %s: generated source does not match %s", n.Name, pat)
			}
		}
	}
}

// TestRenderFailsLoudlyOnBadSpec proves format.Source is doing its job: a node
// name that isn't a valid Go identifier must not silently produce a broken file.
func TestRenderFailsLoudlyOnBadSpec(t *testing.T) {
	t.Parallel()

	bad := hierarchy{
		Base: "Expr",
		Noun: "expression",
		Nodes: []node{{
			Name:   "not a valid identifier",
			Fields: []field{{"Value", "any"}},
		}},
	}

	if _, err := render(bad); err == nil {
		t.Fatal("render() succeeded on an invalid node name; format.Source should have rejected it")
	}
}

// firstDiff reports the first differing line, so the failure message is usable.
func firstDiff(want, got string) string {
	w, g := strings.Split(want, "\n"), strings.Split(got, "\n")
	for i := 0; i < len(w) || i < len(g); i++ {
		lw, lg := "<eof>", "<eof>"
		if i < len(w) {
			lw = w[i]
		}
		if i < len(g) {
			lg = g[i]
		}
		if lw != lg {
			return "first difference at line " + itoa(i+1) + ":\n  committed: " + lw + "\n  generated: " + lg
		}
	}
	return "(no line difference — trailing bytes differ)"
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var b []byte
	for ; n > 0; n /= 10 {
		b = append([]byte{byte('0' + n%10)}, b...)
	}
	return string(b)
}
