// Code generated by cmd/genast. DO NOT EDIT.

package ast

import "compiler101/lexer/token"

// Expr is the sealed set of expression nodes. isExpr is unexported, so
// no type outside this package can join the set.
type Expr interface {
	Accept(v ExprVisitor) any
	isExpr()
}

// ExprVisitor is one operation over the tree. Adding a node type below
// breaks every visitor that does not handle it — at compile time, which is the
// whole reason for the pattern.
type ExprVisitor interface {
	VisitBinaryExpr(e *Binary) any
	VisitGroupingExpr(e *Grouping) any
	VisitLiteralExpr(e *Literal) any
	VisitUnaryExpr(e *Unary) any
}

// Binary is an infix operation: Left Operator Right.
type Binary struct {
	Left     Expr
	Operator token.Token
	Right    Expr
}

func (e *Binary) Accept(v ExprVisitor) any { return v.VisitBinaryExpr(e) }
func (e *Binary) isExpr()                  {}

// Grouping is a parenthesised expression. It survives into the tree because
// it changes precedence, and the interpreter must not re-associate across it.
type Grouping struct {
	Expression Expr
}

func (e *Grouping) Accept(v ExprVisitor) any { return v.VisitGroupingExpr(e) }
func (e *Grouping) isExpr()                  {}

// Literal is a bare value: a number, a string, a boolean, or Lox nil.
// Value is nil exactly when the source said nil.
type Literal struct {
	Value any
}

func (e *Literal) Accept(v ExprVisitor) any { return v.VisitLiteralExpr(e) }
func (e *Literal) isExpr()                  {}

// Unary is a prefix operation: Operator Right.
type Unary struct {
	Operator token.Token
	Right    Expr
}

func (e *Unary) Accept(v ExprVisitor) any { return v.VisitUnaryExpr(e) }
func (e *Unary) isExpr()                  {}
