// Code generated by cmd/genast. DO NOT EDIT.

package ast

import "compiler101/lexer/token"

// Stmt is the sealed set of statement nodes. isStmt is unexported, so
// no type outside this package can join the set.
type Stmt interface {
	Accept(v StmtVisitor) any
	isStmt()
}

// StmtVisitor is one operation over the tree. Adding a node type below
// breaks every visitor that does not handle it — at compile time, which is the
// whole reason for the pattern.
type StmtVisitor interface {
	VisitBlockStmt(e *Block) any
	VisitExpressionStmt(e *Expression) any
	VisitIfStmt(e *If) any
	VisitPrintStmt(e *Print) any
	VisitVarStmt(e *Var) any
	VisitWhileStmt(e *While) any
}

// Block executes Statements in a nested lexical scope.
type Block struct {
	Statements []Stmt
}

func (e *Block) Accept(v StmtVisitor) any { return v.VisitBlockStmt(e) }
func (e *Block) isStmt()                  {}

// Expression evaluates an expression for its side effects.
type Expression struct {
	Expression Expr
}

func (e *Expression) Accept(v StmtVisitor) any { return v.VisitExpressionStmt(e) }
func (e *Expression) isStmt()                  {}

// If executes ThenBranch when Condition is truthy, otherwise ElseBranch when present.
type If struct {
	Condition  Expr
	ThenBranch Stmt
	ElseBranch Stmt
}

func (e *If) Accept(v StmtVisitor) any { return v.VisitIfStmt(e) }
func (e *If) isStmt()                  {}

// Print evaluates Expression and writes its Lox representation.
type Print struct {
	Expression Expr
}

func (e *Print) Accept(v StmtVisitor) any { return v.VisitPrintStmt(e) }
func (e *Print) isStmt()                  {}

// Var declares Name, initialized by Initializer or nil when it is absent.
type Var struct {
	Name        token.Token
	Initializer Expr
}

func (e *Var) Accept(v StmtVisitor) any { return v.VisitVarStmt(e) }
func (e *Var) isStmt()                  {}

// While repeatedly executes Body while Condition remains truthy.
type While struct {
	Condition Expr
	Body      Stmt
}

func (e *While) Accept(v StmtVisitor) any { return v.VisitWhileStmt(e) }
func (e *While) isStmt()                  {}
