// Code generated by cmd/genast. DO NOT EDIT.

package ast

import "compiler101/lexer/token"

// Stmt is the sealed set of statement nodes. isStmt is unexported, so
// no type outside this package can join the set.
type Stmt interface {
	Accept(v StmtVisitor) any
	isStmt()
}

// StmtVisitor is one operation over the tree. Adding a node type below
// breaks every visitor that does not handle it — at compile time, which is the
// whole reason for the pattern.
type StmtVisitor interface {
	VisitBlockStmt(e *Block) any
	VisitClassStmt(e *Class) any
	VisitExpressionStmt(e *Expression) any
	VisitFunctionStmt(e *Function) any
	VisitIfStmt(e *If) any
	VisitPrintStmt(e *Print) any
	VisitReturnStmt(e *Return) any
	VisitVarStmt(e *Var) any
	VisitWhileStmt(e *While) any
}

// Block executes Statements in a nested lexical scope.
type Block struct {
	Statements []Stmt
}

func (e *Block) Accept(v StmtVisitor) any { return v.VisitBlockStmt(e) }
func (e *Block) isStmt()                  {}

// Class binds Name to a class whose instances carry Methods and which
// itself carries ClassMethods — the ones declared with a leading `class`.
// Both are *Function rather than Stmt because every consumer wants the
// concrete node: a method is never executed as a statement.
//
// Superclass is nil for a root class. It is *Variable and not Expr because
// the grammar allows nothing else there: a superclass is named, never
// computed, and both the resolver and the runtime want the name.
type Class struct {
	Name         token.Token
	Superclass   *Variable
	Methods      []*Function
	ClassMethods []*Function
}

func (e *Class) Accept(v StmtVisitor) any { return v.VisitClassStmt(e) }
func (e *Class) isStmt()                  {}

// Expression evaluates an expression for its side effects.
type Expression struct {
	Expression Expr
}

func (e *Expression) Accept(v StmtVisitor) any { return v.VisitExpressionStmt(e) }
func (e *Expression) isStmt()                  {}

// Function binds Name to a callable with Params and Body.
//
// IsGetter marks a class body member declared without a parameter list, whose
// body runs on property access rather than on a call. The flag has to live on
// the node because a getter and a zero-parameter method are otherwise
// identical here: both have no Params.
type Function struct {
	Name     token.Token
	Params   []token.Token
	Body     []Stmt
	IsGetter bool
}

func (e *Function) Accept(v StmtVisitor) any { return v.VisitFunctionStmt(e) }
func (e *Function) isStmt()                  {}

// If executes ThenBranch when Condition is truthy, otherwise ElseBranch when present.
type If struct {
	Condition  Expr
	ThenBranch Stmt
	ElseBranch Stmt
}

func (e *If) Accept(v StmtVisitor) any { return v.VisitIfStmt(e) }
func (e *If) isStmt()                  {}

// Print evaluates Expression and writes its Lox representation.
type Print struct {
	Expression Expr
}

func (e *Print) Accept(v StmtVisitor) any { return v.VisitPrintStmt(e) }
func (e *Print) isStmt()                  {}

// Return exits the nearest function, yielding Value or nil when it is absent.
type Return struct {
	Keyword token.Token
	Value   Expr
}

func (e *Return) Accept(v StmtVisitor) any { return v.VisitReturnStmt(e) }
func (e *Return) isStmt()                  {}

// Var declares Name, initialized by Initializer or nil when it is absent.
type Var struct {
	Name        token.Token
	Initializer Expr
}

func (e *Var) Accept(v StmtVisitor) any { return v.VisitVarStmt(e) }
func (e *Var) isStmt()                  {}

// While repeatedly executes Body while Condition remains truthy.
type While struct {
	Condition Expr
	Body      Stmt
}

func (e *While) Accept(v StmtVisitor) any { return v.VisitWhileStmt(e) }
func (e *While) isStmt()                  {}
